# To create an environment from this file using conda, run:
# conda env create -f environment.yml

name: mps
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask=3.0.3
  - requests=2.32.3

