name: Sync Data Folder

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "montanus-wecib"
        git config --global user.email "amontanus@wcpss.net" 

    - name: Sync data folder
      run: |
        # Copy the data folder to the MPS-data repo (if this is a separate directory in your project)
        cp -r ./data /tmp/data-folder  # Adjust this path to your local data folder
        cd /tmp/data-folder
        git init
        git remote add data https://github.com/montanus-wecib/MPS-data.git  # Use your repo URL
        git add .
        git commit -m "Sync data folder"
        git push https://${{ secrets.GH_TOKEN }}@github.com/montanus-wecib/MPS-data.git HEAD:main
y
