name: Sync data folder to MPS-data repository

on:
  push:
    paths:
      - 'data/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3

    - name: Add remote for MPS-data
      run: git remote add data https://github.com/montanus-wecib/MPS-data.git

    - name: Set up Git
      run: |
        git config --global user.name "montanus-wecib"
        git config --global user.email "amontanus@wcpss.net"

    - name: Copy data to MPS-data repo
      run: |
        git clone https://github.com/montanus-wecib/MPS-data.git
        cp -r data/* MPS-data/

    - name: Commit and push changes to MPS-data repository
      run: |
        cd MPS-data
        git add .
        git commit -m "Sync data folder"
        git push https://github.com/montanus-wecib/MPS-data.git main
